### ISSUE TITLE
Multi-UAV setup script string errors 

### ISSUE THREAD

**Issue by darknight-007** [darknight-007/Firmware#3]
In launch/posix_sitl_multi_tmp.launch , 
note the f110-tmp-1, f220-tmp-2, etc. and also px5, px6, etc (when number of UAVs > 4) 

`<arg name="vehicle1" default="f110-tmp-1"/>
    <arg name="vehicle2" default="f220-tmp-2"/>
    <arg name="vehicle3" default="f330-tmp-3"/>
    <arg name="vehicle4" default="f440-tmp-4"/>
    <arg name="vehicle5" default="f550-tmp-5"/>
    <arg name="vehicle6" default="f660-tmp-6"/>
    <arg name="vehicle7" default="f770-tmp-7"/>
    <arg name="world" default="$(find mavlink_sitl_gazebo)/worlds/empty.world"/>
    <arg name="sdf1" default="$(find mavlink_sitl_gazebo)/models/$(arg vehicle1)/$(arg vehicle1).sdf"/>
    <arg name="rcS1" default="$(find px4)/posix-configs/SITL/init/$(arg est)/$(arg vehicle1)"/>
    <arg name="sdf2" default="$(find mavlink_sitl_gazebo)/models/$(arg vehicle2)/$(arg vehicle2).sdf"/>
    <arg name="rcS2" default="$(find px4)/posix-configs/SITL/init/$(arg est)/$(arg vehicle2)"/>
    <arg name="sdf3" default="$(find mavlink_sitl_gazebo)/models/$(arg vehicle3)/$(arg vehicle3).sdf"/>
    <arg name="rcS3" default="$(find px4)/posix-configs/SITL/init/$(arg est)/$(arg vehicle3)"/>
    <arg name="sdf4" default="$(find mavlink_sitl_gazebo)/models/$(arg vehicle4)/$(arg vehicle4).sdf"/>
    <arg name="rcS4" default="$(find px4)/posix-configs/SITL/init/$(arg est)/$(arg vehicle4)"/>
    <arg name="sdf5" default="$(find mavlink_sitl_gazebo)/models/$(arg vehicle5)/$(arg vehicle5).sdf"/>
    <arg name="rcS5" default="$(find px5)/posix-configs/SITL/init/$(arg est)/$(arg vehicle5)"/>
    <arg name="sdf6" default="$(find mavlink_sitl_gazebo)/models/$(arg vehicle6)/$(arg vehicle6).sdf"/>
    <arg name="rcS6" default="$(find px6)/posix-configs/SITL/init/$(arg est)/$(arg vehicle6)"/>
    <arg name="sdf7" default="$(find mavlink_sitl_gazebo)/models/$(arg vehicle7)/$(arg vehicle7).sdf"/>
    <arg name="rcS7" default="$(find px7)/posix-configs/SITL/init/$(arg est)/$(arg vehicle7)"/>`

**Comment by schmittlema** [comment]
https://github.com/darknight-007/Firmware/commit/6390be031b5eafb2ba0897a589e121b9ae60c2b9

**Comment by darknight-007** [comment]
Works, with one  error. 

root@4144932b98bd:~/src/Firmware/Tools# roslaunch px4 posix_sitl_multi_tmp.launch headless:=true gui:=false
... logging to /root/.ros/log/4c0395c0-6638-11e7-86d1-0242ac110003/roslaunch-4144932b98bd-23416.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

[/root/catkin_ws/src/Firmware/launch/posix_sitl_multi_tmp.launch] requires the 'x1' arg to be set
The traceback for the exception was written to the log file

**Comment by schmittlema** [comment]
https://github.com/darknight-007/Firmware/commit/64710ae4d1867b701c49adea4dc7a02c1de2ad3f
